import { ClientOnly } from "./components/ClientOnly";
import { Navbar } from "./components/navbar/Navbar";

import { Nunito } from "next/font/google";
import { RegisterModal } from "./components/modals/RegisterModal";
import { LoginModal } from "./components/modals/LoginModal";
import { RentModal } from "./components/modals/RentModal";
import { ToasterProvider } from "./providers/ToasterProvider";

import getCurrentUser from "./actions/getCurrentUser";

import "./globals.css";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <RegisterModal />
          <LoginModal />
          <RentModal />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
